#!/bin/bash
# probar.sh <base-local> — aserciones del bloque 1 sobre una COPIA ya migrada y sembrada.
# Contra la copia SIN migrar tiene que fallar: así se prueba que el guardián grita.
# Cada caso corre en su transacción con ROLLBACK (los cambios de preparación incluidos).
set -uo pipefail
L="postgresql://$(whoami)@localhost:5432/${1:?base}"
FALLAS=0; N=0
claims() { [ "$1" = sinrol ] && { echo '{"role":"authenticated"}'; return; }
  [ "$1" = _servicio ] && { echo '{"role":"service_role"}'; return; }
  [ "$1" = _dueno ] && { echo '{}'; return; }
  echo "{\"role\":\"authenticated\",\"sub\":\"$(psql -X -At "$L" -c "select md5('kx-$1')::uuid")\",\"email\":\"$1@prueba.kx\",\"app_metadata\":{\"role\":\"$1\"}}"; }
# caso <nombre> <esperado> <rol> <preparación-como-dueño> <consulta-como-rol>
caso() {
  local nom="$1" esp="$2" rol="$3" prep="$4" q="$5" v
  v=$(psql -X -At -v ON_ERROR_STOP=1 "$L" 2>&1 <<SQL
begin;
$prep
select set_config('request.jwt.claims', '$(claims "$rol")', true) \gset
$( [ "$rol" = _dueno ] && echo "-- dueño: sin cambiar de rol" || { [ "$rol" = _servicio ] && echo "set local role service_role;" || echo "set local role authenticated;"; } )
$q
rollback;
SQL
) ; if printf '%s' "$v" | grep -q 'ERROR:'; then v=$(printf '%s\n' "$v" | grep -m1 'ERROR:' | sed 's/.*ERROR: */ERROR: /'); else v=$(printf '%s\n' "$v" | grep -vE '^(BEGIN|ROLLBACK|SET|UPDATE [0-9]+|INSERT 0 [0-9]+)$' | grep -v '^$' | tail -1); fi
  N=$((N+1))
  if [ "$v" = "$esp" ] || { [ "$esp" = ERROR ] && [ "${v#ERROR}" != "$v" ]; }; then echo "  ✅ $nom"; else echo "  🔴 $nom — esperaba «${esp}», dio «${v}»"; FALLAS=$((FALLAS+1)); fi
}
ATAR="update funnel_agentes set user_id=md5('kx-telemarketing')::uuid where id=900002;
      update funnel_agentes set user_id=md5('kx-otroB')::uuid where id=900003;
      update funnel_agentes set user_id=md5('kx-otroC')::uuid where id=900004;
      update funnel_agentes set user_id=md5('kx-supervisor_tmk')::uuid where id=900001;"
PROS="select coalesce(string_agg(nombre,',' order by nombre),'-') from funnel_prospectos where id>=900100;"
LISTA="select coalesce(string_agg(nombre,',' order by nombre),'-') from funnel_tmk_mi_lista() where id>=900100;"

echo "· identidad por cuenta, no por correo"
caso "tmk atado ve SOLO lo suyo (no pX, que comparte su correo) — por su lista" "pA" telemarketing "$ATAR" "$LISTA"
caso "tmk atado no edita la tabla directo (bloque 2: solo por funnel_tmk_resultado)" "-" telemarketing "$ATAR" "with u as (update funnel_prospectos set comentario='x' where id>=900100 returning nombre) select coalesce(string_agg(nombre,','),'-') from u;"
caso "tmk no se reasigna un prospecto (no toca ninguna fila)" "0" telemarketing "$ATAR" "with u as (update funnel_prospectos set tmk_id=900003 where id=900101 returning 1) select count(*) from u;"
caso "tmk ve SOLO sus comisiones" "900201" telemarketing "$ATAR" "select coalesce(string_agg(id::text,','),'-') from funnel_comisiones where id>=900200;"
caso "cuenta sin agente atado no ve prospectos" "-" telemarketing "" "$PROS"
caso "cliente no ve comisiones aunque se le ate nada" "-" cliente "$ATAR" "select coalesce(string_agg(id::text,','),'-') from funnel_comisiones where id>=900200;"

echo "· equipo (supervisor sin bandera de gerente, el caso del issue #48)"
caso "supervisor_tmk ve a su equipo (A y B), no a C ni X" "pA,pB" supervisor_tmk "$ATAR update funnel_roles set es_gerente=false where clave='supervisor_tmk';" "$PROS"
caso "tmk no pide el organigrama de otro" "0" telemarketing "$ATAR" "select count(*) from funnel_ve_equipo(900001);"
caso "gerente sí puede pedir el organigrama de otro" "3" gerente_tmk "$ATAR" "select count(*) from funnel_ve_equipo(900001);"

echo "· un solo sistema de roles"
caso "no se ata un agente de rol distinto al de la cuenta" "ERROR" admin "" "update funnel_agentes set user_id=md5('kx-vendedor')::uuid where id=900002;"
caso "sí se ata cuando el rol calza (vendedor→vendedor)" "1" admin "update funnel_agentes set rol='vendedor' where id=900005;" "with u as (update funnel_agentes set user_id=md5('kx-vendedor')::uuid where id=900005 returning 1) select count(*) from u;"
caso "una cuenta no se ata a dos agentes" "ERROR" admin "$ATAR" "update funnel_agentes set user_id=md5('kx-telemarketing')::uuid where id=900005;"
caso "etiqueta de George: liner" "Liner (vendedor)" admin "" "select nombre from funnel_roles where clave='vendedor';"

caso "alta desde la pantalla ata la cuenta sola (correo + rol que calza)" "t" gerente_tmk "" "with i as (insert into funnel_agentes(nombre,rol,email,peso) values ('Nuevo','tmk','Telemarketing@prueba.kx',1) returning user_id) select coalesce(user_id = md5('kx-telemarketing')::uuid,false) from i;"
caso "alta con rol que no calza queda sin cuenta (y en avisos)" "t" gerente_tmk "" "with i as (insert into funnel_agentes(nombre,rol,email,peso) values ('Nuevo','vendedor','otrob@prueba.kx',1) returning user_id) select user_id is null from i;"
caso "alta de una cuenta que ya tiene agente activo no la roba" "t" gerente_tmk "$ATAR" "with i as (insert into funnel_agentes(nombre,rol,email,peso) values ('Dup','tmk','otrob@prueba.kx',1) returning user_id) select user_id is null from i;"
caso "el recién atado ve su prospecto (y no pX, que comparte su correo)" "pNuevo" telemarketing "insert into funnel_agentes(id,nombre,rol,email,peso) overriding system value values (900009,'Nuevo','tmk','telemarketing@prueba.kx',1); insert into funnel_prospectos(id,nombre,tmk_id) overriding system value values (900109,'pNuevo',900009);" "$LISTA"

echo "· la matriz de la pestaña Roles manda"
caso "quitar ver_socios a telemarketing lo deja en 0" "0" telemarketing "update funnel_permisos set permitido=false where rol_clave='telemarketing' and permiso='ver_socios';" "select count(*) from socios;"
caso "dar editar_socios a telemarketing lo deja editar" "1" telemarketing "update funnel_permisos set permitido=true where rol_clave='telemarketing' and permiso='editar_socios';" "with u as (update socios set estado=estado where id=(select min(id) from public.socios) returning 1) select count(*) from u;"
caso "sin editar_socios telemarketing no edita" "0" telemarketing "" "with u as (update socios set estado=estado where id=(select min(id) from public.socios) returning 1) select count(*) from u;"
caso "quitar ver_comisiones a gerente_tmk: ya no ve las ajenas" "-" gerente_tmk "update funnel_permisos set permitido=false where rol_clave='gerente_tmk' and permiso='ver_comisiones';" "select coalesce(string_agg(id::text,','),'-') from funnel_comisiones where id>=900200;"
caso "quitar gestionar_comisiones a supervisor: no edita reglas" "0" supervisor "update funnel_permisos set permitido=false where rol_clave='supervisor' and permiso='gestionar_comisiones';" "with u as (update funnel_comision_reglas set activo=activo returning 1) select count(*) from u;"
caso "quitar cerrar_contrato a vendedor: no cierra" "ERROR: no autorizado" vendedor "update funnel_permisos set permitido=false where rol_clave='vendedor' and permiso='cerrar_contrato';" "select funnel_cerrar_contrato(900101,'x','x',1) is null;"
caso "rol apagado no puede nada" "f" gerente_ventas "update funnel_roles set activo=false where clave='gerente_ventas';" "select funnel_puede('editar_socios');"
caso "cambio de rol: baja del agente viejo + agente nuevo con la misma cuenta" "1" admin "$ATAR update funnel_agentes set activo=false where id=900002; update auth.users set raw_app_meta_data='{\"role\":\"vendedor\"}' where id=md5('kx-telemarketing')::uuid;" "with i as (insert into funnel_agentes(nombre,rol,email,activo,peso,user_id) values ('A liner','vendedor','telemarketing@prueba.kx',true,1,md5('kx-telemarketing')::uuid) returning 1) select count(*) from i;"
caso "telemarketing no se da permisos solo" "0" telemarketing "" "with u as (update funnel_permisos set permitido=true where rol_clave='telemarketing' and permiso='editar_socios' returning 1) select count(*) from u;"
caso "telemarketing no ve los avisos" "0" telemarketing "" "select count(*) from funnel_descalces();"
caso "un gerente sin «gestionar roles» no ve correos de login en avisos" "0" gerente_tmk "" "select count(*) from funnel_descalces();"
caso "el admin sí ve los avisos" "t" admin "" "select count(*)>0 from funnel_descalces();"
caso "el admin no se puede apagar (no se encierra)" "ERROR" admin "" "update funnel_roles set activo=false where clave='admin';"
caso "el admin no pierde «gestionar roles»" "ERROR" admin "" "update funnel_permisos set permitido=false where rol_clave='admin' and permiso='gestionar_roles';"
caso "otros roles sí se apagan" "1" admin "" "with u as (update funnel_roles set activo=false where clave='servicio' returning 1) select count(*) from u;"
caso "la vista de descalces no se lee directo" "ERROR" gerente_tmk "" "select count(*) from funnel_equipo_descalces;"

echo "· paso 3: personas (alta desde el panel)"
NUEVA="insert into auth.users(id,email,raw_app_meta_data) values (md5('kx-nueva')::uuid,'nueva@prueba.kx','{\"role\":\"telemarketing\"}');"
ALTA="$NUEVA select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'alta', 'Nueva Persona', 'telemarketing', 900001);"
caso "telemarketing no lista personas" "ERROR" telemarketing "" "select count(*) from funnel_personas_listar();"
caso "admin lista personas" "t" admin "" "select count(*)>0 from funnel_personas_listar();"
caso "la lista no trae cuentas de socios" "0" admin "" "select count(*) from funnel_personas_listar() where rol='cliente';"
caso "el panel sabe si puedo (telemarketing: no)" "false" telemarketing "" "select funnel_personas_puedo()->>'puede';"
caso "el panel sabe si puedo (admin: sí)" "true" admin "" "select funnel_personas_puedo()->>'puede';"
caso "una cuenta del equipo NO puede registrar (solo el servidor)" "ERROR" admin "$NUEVA" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'alta', 'X', 'telemarketing', null);"
caso "alta: nace su agente tmk, atado y con su jefe" "tmk|t|900001|Nueva Persona" _dueno "$ALTA" "select rol, user_id is not null, supervisor_id, nombre from funnel_agentes where email='nueva@prueba.kx' and activo;"
caso "alta: queda en la bitácora" "1" _dueno "$ALTA" "select count(*) from funnel_personas_bitacora where persona=md5('kx-nueva')::uuid and accion='alta';"
caso "el servidor SÍ puede registrar (y un alta no cierra sesiones)" "0" _servicio "$NUEVA" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'alta', 'X', 'telemarketing', null);"
caso "alta con un rol que la cuenta no tiene: frena" "ERROR" _servicio "$NUEVA" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'alta', 'X', 'vendedor', null);"
caso "alta con un jefe que no existe: frena" "ERROR" _servicio "$NUEVA" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'alta', 'X', 'telemarketing', 424242);"
caso "nada sobre uno mismo" "ERROR" _servicio "" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-admin')::uuid, 'desactivar');"
caso "cambiar a liner: el tmk se da de baja y nace un vendedor" "vendedor" _dueno "$ALTA update auth.users set raw_app_meta_data='{\"role\":\"vendedor\"}' where id=md5('kx-nueva')::uuid; select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'cambiar_rol', null, 'vendedor', null);" "select string_agg(rol,',') from funnel_agentes where user_id=md5('kx-nueva')::uuid and activo;"
caso "cambiar el rol cierra sus sesiones" "2" _servicio "$ALTA insert into auth.sessions(user_id) values (md5('kx-nueva')::uuid),(md5('kx-nueva')::uuid); update auth.users set raw_app_meta_data='{\"role\":\"vendedor\"}' where id=md5('kx-nueva')::uuid;" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'cambiar_rol', null, 'vendedor', null);"
caso "pasar a hostess (bloque 4: la hostess es agente para estar en un turno): un solo agente activo, de recepción" "1|recepcion" _dueno "$ALTA update auth.users set raw_app_meta_data='{\"role\":\"recepcion\"}' where id=md5('kx-nueva')::uuid; select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'cambiar_rol', null, 'recepcion', null);" "select count(*)||'|'||max(rol) from funnel_agentes where user_id=md5('kx-nueva')::uuid and activo;"
caso "desactivar cierra sus sesiones" "1" _dueno "$ALTA insert into auth.sessions(user_id) values (md5('kx-nueva')::uuid);" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'desactivar');"
caso "desactivar da de baja su agente" "0" _dueno "$ALTA select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'desactivar');" "select count(*) from funnel_agentes where user_id=md5('kx-nueva')::uuid and activo;"
caso "activar: vuelve su agente" "1" _dueno "$ALTA select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'desactivar'); select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'activar');" "select count(*) from funnel_agentes where user_id=md5('kx-nueva')::uuid and activo;"
LEGADO="insert into funnel_agentes(id,nombre,rol,email,activo,peso,supervisor_id) overriding system value values (900050,'Legado','tmk','nueva@prueba.kx',true,1,900001); insert into funnel_prospectos(id,nombre,tmk_id) overriding system value values (900150,'pLegado',900050);"
caso "alta de alguien que YA estaba en el equipo: adopta su agente (no crea otro)" "900050|1" _dueno "$LEGADO $NUEVA select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'alta', 'Nueva', 'telemarketing', null);" "select min(id)||'|'||count(*) from funnel_agentes where lower(email)='nueva@prueba.kx' and activo;"
caso "el adoptado conserva su jefe si no se eligió otro" "900001" _dueno "$LEGADO $NUEVA select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'alta', 'Nueva', 'telemarketing', null);" "select supervisor_id from funnel_agentes where id=900050;"
caso "sus prospectos de antes quedan con su cuenta nueva" "t" _dueno "$LEGADO $NUEVA select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'alta', 'Nueva', 'telemarketing', null);" "select (select user_id from funnel_agentes a join funnel_prospectos p on p.tmk_id=a.id where p.id=900150) = md5('kx-nueva')::uuid;"
caso "dos agentes sin cuenta con el mismo correo: no adivina (frena)" "ERROR" _dueno "$LEGADO insert into funnel_agentes(nombre,rol,email,activo,peso) values ('Legado2','tmk','NUEVA@prueba.kx',true,1); $NUEVA" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'alta', 'Nueva', 'telemarketing', null);"
caso "adoptarlo poniéndolo de su propio jefe: frena" "ERROR" _dueno "$LEGADO $NUEVA" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'alta', 'Nueva', 'telemarketing', 900050);"
caso "cambiar el rol de una cuenta desactivada: frena (no vuelve al reparto)" "ERROR" _dueno "$ALTA update auth.users set banned_until=now()+interval '100 years', raw_app_meta_data='{\"role\":\"vendedor\"}' where id=md5('kx-nueva')::uuid;" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'cambiar_rol', null, 'vendedor', null);"
caso "se le puede QUITAR el jefe" "sin jefe" _dueno "$ALTA select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'cambiar_rol', null, 'telemarketing', null, true);" "select coalesce(supervisor_id::text,'sin jefe') from funnel_agentes where user_id=md5('kx-nueva')::uuid and activo;"
caso "sin pedir cambio de jefe, lo conserva" "900001" _dueno "$ALTA select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'cambiar_rol', null, 'telemarketing', null);" "select supervisor_id from funnel_agentes where user_id=md5('kx-nueva')::uuid and activo;"
caso "nadie es su propio jefe" "ERROR" _dueno "$ALTA" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'cambiar_rol', null, 'telemarketing', (select id from funnel_agentes where user_id=md5('kx-nueva')::uuid and activo), true);"
caso "reenviar enlace no corta sesiones (la clave no cambió)" "0" _dueno "$ALTA insert into auth.sessions(user_id) values (md5('kx-nueva')::uuid);" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'restablecer');"
caso "alta de alguien que ya está con OTRO rol y sin cuenta: frena (no duplica)" "ERROR" _dueno "$LEGADO insert into auth.users(id,email,raw_app_meta_data) values (md5('kx-otro')::uuid,'nueva@prueba.kx','{\"role\":\"vendedor\"}');" "select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-otro')::uuid, 'alta', 'X', 'vendedor', null);"
caso "adopta aunque el correo del agente tenga espacios o mayúsculas" "900050" _dueno "$LEGADO update funnel_agentes set email='  NUEVA@prueba.kx ' where id=900050; $NUEVA select funnel_personas_registrar(md5('kx-admin')::uuid, md5('kx-nueva')::uuid, 'alta', 'Nueva', 'telemarketing', null);" "select id from funnel_agentes where user_id=md5('kx-nueva')::uuid and activo;"
caso "telemarketing no lee la bitácora" "0" telemarketing "" "select count(*) from funnel_personas_bitacora;"
caso "nadie del equipo escribe la bitácora" "ERROR" admin "" "insert into funnel_personas_bitacora(actor,persona,accion) values (md5('kx-admin')::uuid, md5('kx-admin')::uuid, 'alta');"
caso "permiso nuevo: solo admin gestiona personas" "admin" admin "" "select string_agg(rol_clave,',') from funnel_permisos where permiso='gestionar_personas' and permitido;"

echo "· bloque 2: telemarketing"
RES="select funnel_tmk_resultado"
DUE="reset role;"
CUANDO="date_trunc('hour',now()+interval '1 day')"
HOR="insert into funnel_horarios(restaurante_id,dia_semana,hora,cupo) select (select min(id) from funnel_restaurantes where activo), extract(dow from ($CUANDO at time zone 'America/Guatemala'))::int, ($CUANDO at time zone 'America/Guatemala')::time, 2 on conflict do nothing;"
SOLO3="update funnel_agentes set activo=false where rol='tmk' and id not in (900002,900003,900004);"
caso "tmk no lee la tabla directo" "-" telemarketing "$ATAR" "$PROS"
caso "su lista trae SOLO lo mínimo (sin correo, edad, tarjetas…)" "comentario,es_socio,estado,id,intentos,nombre,presenta_en,recontacto_en,restaurante_id,telefono" telemarketing "$ATAR" "select string_agg(k,',' order by k) from (select jsonb_object_keys(to_jsonb(l)) k from funnel_tmk_mi_lista() l where id=900101) s;"
caso "cuenta sin agente: lista vacía" "-" telemarketing "" "$LISTA"
caso "contestó: interesado y socio" "interesado|true" telemarketing "$ATAR" "$RES(900101,'interesado',true); select estado||'|'||es_socio from funnel_tmk_mi_lista() where id=900101;"
caso "contestó: no interesado y no socio" "no_interesado|false" telemarketing "$ATAR" "$RES(900101,'no_interesado',false); select estado||'|'||es_socio from funnel_tmk_mi_lista() where id=900101;"
caso "no anota sobre el prospecto de otro" "ERROR" telemarketing "$ATAR" "$RES(900102,'interesado');"
caso "no contestó: pasa a OTRO telemarketer activo, intento 1" "true|1|no_contesta" telemarketing "$ATAR" "$RES(900101,'no_contesta'); $DUE select (tmk_id<>900002 and tmk_id in (select id from funnel_agentes where activo and rol='tmk'))::text||'|'||intentos_sin_respuesta||'|'||estado from funnel_prospectos where id=900101;"
caso "no contestó: sale de mi lista" "-" telemarketing "$ATAR" "$RES(900101,'no_contesta'); $LISTA"
caso "no repite al que ya lo intentó (B ya llamó → le toca a C)" "900004" telemarketing "$ATAR $SOLO3 insert into funnel_eventos(prospecto_id,tipo,payload) values (900101,'no_contesta','{\"tmk_id\":900003}');" "$RES(900101,'no_contesta'); $DUE select tmk_id from funnel_prospectos where id=900101;"
caso "si ya lo intentaron todos, a otro que no sea yo" "900003" telemarketing "$ATAR update funnel_agentes set activo=false where rol='tmk' and id not in (900002,900003); insert into funnel_eventos(prospecto_id,tipo,payload) values (900101,'no_contesta','{\"tmk_id\":900003}');" "$RES(900101,'no_contesta'); $DUE select tmk_id from funnel_prospectos where id=900101;"
caso "si no hay otro telemarketer, se queda conmigo" "900002|no_contesta" telemarketing "$ATAR update funnel_agentes set activo=false where rol='tmk' and id<>900002;" "$RES(900101,'no_contesta'); $DUE select tmk_id||'|'||estado from funnel_prospectos where id=900101;"
caso "al 3er intento: no contactable (y no cambia de dueño)" "no_contactable|3|900002" telemarketing "$ATAR update funnel_prospectos set intentos_sin_respuesta=2 where id=900101;" "$RES(900101,'no_contesta'); $DUE select estado||'|'||intentos_sin_respuesta||'|'||tmk_id from funnel_prospectos where id=900101;"
caso "gerencia baja el tope a 2: al 2do intento, no contactable" "no_contactable" telemarketing "$ATAR update funnel_parametros set valor=2 where clave='tmk_intentos_max'; update funnel_prospectos set intentos_sin_respuesta=1 where id=900101;" "$RES(900101,'no_contesta'); $DUE select estado from funnel_prospectos where id=900101;"
caso "no contactable ya no aparece en la lista" "-" telemarketing "$ATAR update funnel_prospectos set estado='no_contactable' where id=900101;" "$LISTA"
caso "sobre un no contactable, el telemarketer no anota" "ERROR" telemarketing "$ATAR update funnel_prospectos set estado='no_contactable' where id=900101;" "$RES(900101,'interesado');"
caso "contestar pone los intentos en 0" "0" telemarketing "$ATAR update funnel_prospectos set intentos_sin_respuesta=2 where id=900101;" "$RES(900101,'interesado'); select intentos from funnel_tmk_mi_lista() where id=900101;"
caso "reprogramar: se queda con el MISMO, a esa hora" "recontactar|900002|true" telemarketing "$ATAR" "$RES(900101,'reprogramar',null,now()+interval '2 hours'); $DUE select estado||'|'||tmk_id||'|'||(abs(extract(epoch from recontacto_en-(now()+interval '2 hours')))<5)::text from funnel_prospectos where id=900101;"
caso "reprogramar sin fecha: frena" "ERROR" telemarketing "$ATAR" "$RES(900101,'reprogramar');"
caso "reprogramar a una hora que ya pasó: frena" "ERROR" telemarketing "$ATAR" "$RES(900101,'reprogramar',null,now()-interval '1 day');"
caso "reprogramar a más de 6 meses: frena" "ERROR" telemarketing "$ATAR" "$RES(900101,'reprogramar',null,now()+interval '1 year');"
caso "citar: restaurante + día → asistirá" "asistira" telemarketing "$ATAR $HOR" "$RES(900101,'citar',true,$CUANDO,(select min(id) from funnel_restaurantes where activo)); select estado from funnel_tmk_mi_lista() where id=900101;"
caso "citar sin restaurante: frena" "ERROR" telemarketing "$ATAR $HOR" "$RES(900101,'citar',true,$CUANDO);"
caso "resultado inventado: frena" "ERROR" telemarketing "$ATAR" "$RES(900101,'vendido');"
caso "nota: queda el comentario" "llamar después de las 5" telemarketing "$ATAR" "$RES(900101,'nota',null,null,null,'  llamar después de las 5 '); select comentario from funnel_tmk_mi_lista() where id=900101;"
caso "nota vacía: frena" "ERROR" telemarketing "$ATAR" "$RES(900101,'nota',null,null,null,'   ');"
caso "fuera de telemarketing (ya en sala): frena" "ERROR" telemarketing "$ATAR update funnel_prospectos set etapa='sala' where id=900101;" "$RES(900101,'interesado');"
caso "queda en la bitácora quién llamó y a quién pasó" "900002|true" telemarketing "$ATAR" "$RES(900101,'no_contesta'); $DUE select (payload->>'tmk_id')||'|'||(payload ? 'pasa_a')::text from funnel_eventos where prospecto_id=900101 and tipo='no_contesta';"
caso "supervisor (sin bandera de gerente) anota sobre su equipo" "interesado" supervisor_tmk "$ATAR update funnel_roles set es_gerente=false where clave='supervisor_tmk';" "$RES(900102,'interesado'); $DUE select estado from funnel_prospectos where id=900102;"
caso "supervisor no anota fuera de su equipo" "ERROR" supervisor_tmk "$ATAR update funnel_roles set es_gerente=false where clave='supervisor_tmk';" "$RES(900103,'interesado');"
caso "gerencia anota sobre cualquiera" "interesado" gerente_tmk "$ATAR" "$RES(900103,'interesado'); $DUE select estado from funnel_prospectos where id=900103;"
caso "tmk no cambia el tope" "0" telemarketing "$ATAR" "with u as (update funnel_parametros set valor=5 returning 1) select count(*) from u;"
caso "gerencia sí cambia el tope" "1" gerente_tmk "" "with u as (update funnel_parametros set valor=2 where clave='tmk_intentos_max' returning 1) select count(*) from u;"
caso "el tope no baja de 2 ni sube de 5" "ERROR" gerente_tmk "" "update funnel_parametros set valor=9 where clave='tmk_intentos_max';"
caso "anónimo no llama a las funciones nuevas" "false|false" _dueno "" "select has_function_privilege('anon','public.funnel_tmk_resultado(bigint,text,boolean,timestamptz,bigint,text)','execute')::text||'|'||has_function_privilege('anon','public.funnel_tmk_mi_lista()','execute')::text;"
caso "no contestó: nunca a un agente SIN cuenta (X no tiene)" "900002" telemarketing "$ATAR update funnel_agentes set activo=false where rol='tmk' and id not in (900002,900005);" "$RES(900101,'no_contesta'); $DUE select tmk_id from funnel_prospectos where id=900101;"
caso "citado y después no contestó: la cita se borra" "true" telemarketing "$ATAR $HOR" "$RES(900101,'citar',true,$CUANDO,(select min(id) from funnel_restaurantes where activo)); $RES(900101,'no_contesta'); $DUE select (presenta_en is null and restaurante_id is null)::text from funnel_prospectos where id=900101;"
caso "citado y después no interesado: la cita se borra" "true" telemarketing "$ATAR $HOR" "$RES(900101,'citar',true,$CUANDO,(select min(id) from funnel_restaurantes where activo)); $RES(900101,'no_interesado',false); $DUE select (presenta_en is null)::text from funnel_prospectos where id=900101;"
caso "citar a una hora que ya pasó hace 30 min: frena" "ERROR" telemarketing "$ATAR" "$RES(900101,'citar',true,now()-interval '30 minutes',(select min(id) from funnel_restaurantes where activo));"
caso "tmk no falsea la bitácora que decide la reasignación" "ERROR" telemarketing "$ATAR" "insert into funnel_eventos(prospecto_id,tipo,payload) values (900102,'no_contesta','{\"tmk_id\":900004}');"
caso "tmk sí anota que llamó o escribió (contacto) sobre lo suyo" "1" telemarketing "$ATAR" "with i as (insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900101,'contacto','telemarketing@prueba.kx','{}') returning 1) select count(*) from i;"
caso "prospecto sin dueño + no contestó (gerencia): va a alguien con cuenta" "true" gerente_tmk "$ATAR" "$RES(900105,'no_contesta'); $DUE select (tmk_id in (select id from funnel_agentes where activo and user_id is not null))::text from funnel_prospectos where id=900105;"
caso "S1: tmk no anota sobre un prospecto SIN dueño" "ERROR" telemarketing "$ATAR $HOR" "$RES(900105,'citar',true,$CUANDO,(select min(id) from funnel_restaurantes where activo));"
caso "S1: tmk no se queda un prospecto sin dueño con «no contestó»" "ERROR" telemarketing "$ATAR" "$RES(900105,'no_contesta');"
caso "S1: supervisor (sin bandera) no toca prospectos sin dueño" "ERROR" supervisor_tmk "$ATAR update funnel_roles set es_gerente=false where clave='supervisor_tmk';" "$RES(900105,'interesado');"
caso "id que no existe: mismo mensaje que uno ajeno" "ERROR: no autorizado" telemarketing "$ATAR" "$RES(123456789,'interesado');"
caso "tmk no anota «contacto» sobre un prospecto ajeno" "ERROR" telemarketing "$ATAR" "insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900102,'contacto','telemarketing@prueba.kx','{}');"
caso "tmk no firma la bitácora como «sistema»" "ERROR" telemarketing "$ATAR" "insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900101,'contacto','sistema','{}');"
caso "anónimo no llama al reparto" "false" _dueno "" "select has_function_privilege('anon','public.funnel_repartir(bigint)','execute')::text;"
caso "gerencia anota «asignado» firmado con su correo (reparto de la pantalla)" "1" gerente_tmk "$ATAR" "with i as (insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900101,'asignado','gerente_tmk@prueba.kx','{}') returning 1) select count(*) from i;"
caso "gerencia no firma como «sistema»" "ERROR" gerente_tmk "" "insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900101,'asignado','sistema','{}');"
caso "tipo reservado disfrazado (mayúscula/espacio): frena" "ERROR" gerente_tmk "" "insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900101,'No_contesta ','gerente_tmk@prueba.kx','{}');"
caso "evento sin prospecto: frena" "ERROR" gerente_tmk "" "insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (null,'contacto','gerente_tmk@prueba.kx','{}');"
caso "supervisor no anota sobre un prospecto que no ve" "ERROR" supervisor_tmk "$ATAR update funnel_roles set es_gerente=false where clave='supervisor_tmk';" "insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900103,'contacto','supervisor_tmk@prueba.kx','{}');"
caso "tmk no vacía la bitácora con TRUNCATE" "ERROR" telemarketing "$ATAR" "truncate funnel_eventos;"
caso "tmk no reparte" "ERROR" telemarketing "$ATAR" "select funnel_repartir(1);"
REP9="$ATAR $SOLO3 insert into funnel_bases(id,nombre,total) overriding system value values (900301,'b9',9); insert into funnel_prospectos(nombre,base_id) select 'r'||g,900301 from generate_series(1,9) g;"
caso "reparto: nunca a un agente sin cuenta" "0" gerente_tmk "$REP9 update funnel_agentes set activo=true where id=900005;" "select funnel_repartir(900301); $DUE select count(*) from funnel_prospectos where base_id=900301 and tmk_id=900005;"
caso "reparto parejo: 9 entre 3 con cuenta → 3/3/3" "3,3,3" gerente_tmk "$REP9" "select funnel_repartir(900301); $DUE select string_agg(n::text,',') from (select count(*) n from funnel_prospectos where base_id=900301 group by tmk_id) s;"
caso "reparto al azar: 12 repartos de la misma base no salen todos iguales" "true" _dueno "$REP9" "select set_config('request.jwt.claims','{\"role\":\"authenticated\",\"app_metadata\":{\"role\":\"admin\"}}',true); do \$\$ declare i int; s text; v text[]:='{}'; begin for i in 1..12 loop update funnel_prospectos set tmk_id=null where base_id=900301; perform funnel_repartir(900301); select string_agg(tmk_id::text,',' order by id) into s from funnel_prospectos where base_id=900301; v:=array_append(v,s); end loop; perform set_config('kx.distintos',(select count(distinct x)::text from unnest(v) x),true); end \$\$; select (current_setting('kx.distintos')::int>1)::text;"

echo "· bloque 3: la cita y la carta"
CONF="select funnel_cita_confirmar"
REG="select funnel_cita_regresar"
REST1="(select min(id) from funnel_restaurantes where activo)"
CITADO="$ATAR $HOR update funnel_prospectos set estado='asistira', restaurante_id=$REST1, presenta_en=$CUANDO where id=900101;"
caso "sin horarios no se cita" "ERROR: ese lugar todavía no tiene horarios: pedile al supervisor que los cargue" telemarketing "$ATAR delete from funnel_horarios where restaurante_id=$REST1;" "$RES(900101,'citar',true,$CUANDO,$REST1);"
caso "fuera de horario no se cita" "ERROR: ese día y hora no es un horario del lugar" telemarketing "$ATAR $HOR" "$RES(900101,'citar',true,$CUANDO+interval '1 hour',$REST1);"
caso "horario lleno no se cita (cupo 2)" "ERROR: ese horario ya está lleno" telemarketing "$ATAR $HOR update funnel_prospectos set estado='asistira', restaurante_id=$REST1, presenta_en=$CUANDO where id in (900102,900103);" "$RES(900101,'citar',true,$CUANDO,$REST1);"
caso "la cita del telemarketer nace SIN confirmar" "asistira|true" telemarketing "$ATAR $HOR" "$RES(900101,'citar',true,$CUANDO,$REST1); $DUE select estado||'|'||(cita_confirmada_en is null)::text from funnel_prospectos where id=900101;"
caso "supervisor_tmk confirma (con permiso de la matriz)" "true|true|false" supervisor_tmk "$CITADO" "$CONF(900101,$REST1,$CUANDO,true,false); $DUE select (cita_confirmada_en is not null)::text||'|'||carta_whatsapp||'|'||carta_correo from funnel_prospectos where id=900101;"
caso "telemarketer no confirma" "ERROR: no autorizado" telemarketing "$CITADO" "$CONF(900101,$REST1,$CUANDO,true,false);"
caso "sin el permiso en la matriz, el supervisor no confirma" "ERROR: no autorizado" supervisor_tmk "$CITADO update funnel_permisos set permitido=false where rol_clave='supervisor_tmk' and permiso='confirmar_citas';" "$CONF(900101,$REST1,$CUANDO,true,false);"
caso "confirmar en un horario lleno: frena" "ERROR: ese horario ya está lleno" supervisor_tmk "$CITADO update funnel_prospectos set estado='asistira', restaurante_id=$REST1, presenta_en=$CUANDO where id in (900102,900103);" "$CONF(900101,$REST1,$CUANDO,true,false);"
caso "carta por correo sin correo válido: frena" "ERROR: no tiene un correo válido: no se puede marcar la carta por correo" supervisor_tmk "$CITADO" "$CONF(900101,$REST1,$CUANDO,false,true);"
caso "nadie se autoconfirma editando la fila" "true" gerente_tmk "$CITADO" "update funnel_prospectos set cita_confirmada_en=now(), carta_whatsapp=true where id=900101; $DUE select (cita_confirmada_en is null and not carta_whatsapp)::text from funnel_prospectos where id=900101;"
caso "si cambia la hora, la confirmación se borra sola" "true" supervisor_tmk "$CITADO" "$CONF(900101,$REST1,$CUANDO,true,false); $DUE update funnel_prospectos set presenta_en=presenta_en+interval '1 day' where id=900101; select (cita_confirmada_en is null and not carta_whatsapp)::text from funnel_prospectos where id=900101;"
caso "si deja de estar citado, la confirmación se borra sola" "true" supervisor_tmk "$CITADO" "$CONF(900101,$REST1,$CUANDO,true,false); $DUE update funnel_prospectos set estado='interesado' where id=900101; select (cita_confirmada_en is null)::text from funnel_prospectos where id=900101;"
caso "regresar: vuelve al MISMO telemarketer como interesado, con el motivo" "interesado|900002|Cita regresada: no puede el jueves" supervisor_tmk "$CITADO" "$REG(900101,'no puede el jueves'); $DUE select estado||'|'||tmk_id||'|'||comentario from funnel_prospectos where id=900101;"
caso "regresar sin motivo: frena" "ERROR: escribí el motivo para el telemarketer" supervisor_tmk "$CITADO" "$REG(900101,'  ');"
caso "la lista de citas solo para quien confirma" "ERROR: no autorizado" telemarketing "$CITADO" "select count(*) from funnel_citas_lista();"
caso "la lista de citas trae la pendiente" "1" supervisor_tmk "$CITADO" "select count(*) from funnel_citas_lista() where id=900101 and cita_confirmada_en is null;"
caso "tmk no gestiona lugares" "0" telemarketing "$ATAR" "with u as (update funnel_restaurantes set direccion='x' returning 1) select count(*) from u;"
caso "tmk no crea horarios" "ERROR" telemarketing "$ATAR" "insert into funnel_horarios(restaurante_id,dia_semana,hora) values ($REST1,1,'19:00');"
caso "supervisor_tmk crea horarios" "1" supervisor_tmk "" "with i as (insert into funnel_horarios(restaurante_id,dia_semana,hora,cupo) values ($REST1,1,'19:00',30) returning 1) select count(*) from i;"
caso "mapa solo con https" "ERROR" supervisor_tmk "" "update funnel_restaurantes set mapa_url='javascript:alert(1)' where id=$REST1;"
caso "nadie borra lugares" "ERROR" admin "" "delete from funnel_restaurantes where id=$REST1;"
caso "tmk no firma «cita_confirmada» en la bitácora" "ERROR" gerente_tmk "" "insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900101,'cita_confirmada','gerente_tmk@prueba.kx','{}');"
NOGER="update funnel_roles set es_gerente=false where clave='supervisor_tmk';"
CITADO_C="$ATAR $HOR update funnel_prospectos set estado='asistira', restaurante_id=$REST1, presenta_en=$CUANDO where id in (900101,900103);"
caso "supervisor (sin bandera) no ve citas de otro equipo en su lista" "pA" supervisor_tmk "$CITADO_C $NOGER" "select coalesce(string_agg(nombre,',' order by nombre),'-') from funnel_citas_lista() where id>=900100;"
caso "supervisor (sin bandera) no confirma citas de otro equipo" "ERROR: no autorizado" supervisor_tmk "$CITADO_C $NOGER" "$CONF(900103,$REST1,$CUANDO,false,false);"
caso "supervisor (sin bandera) no regresa citas de otro equipo" "ERROR: no autorizado" supervisor_tmk "$CITADO_C $NOGER" "$REG(900103,'x');"
caso "el cupo se cuenta con candado (dos citas a la vez esperan turno)" "true" _dueno "" "select (pg_get_functiondef('public.funnel_horario_problema(bigint,timestamptz,bigint)'::regprocedure) ilike '%for update%')::text;"
caso "confirmar a más de 6 meses: frena" "ERROR: la fecha queda muy lejos (máximo 6 meses)" supervisor_tmk "$CITADO" "$CONF(900101,$REST1,now()+interval '1 year',false,false);"
caso "si cambian teléfono o correo, el consentimiento se pierde" "true|false|false" supervisor_tmk "$CITADO update funnel_prospectos set email='a@b.gt' where id=900101;" "$CONF(900101,$REST1,$CUANDO,true,true); $DUE update funnel_prospectos set telefono='99999999', email='otro@x.gt' where id=900101; select (cita_confirmada_en is not null)::text||'|'||carta_whatsapp||'|'||carta_correo from funnel_prospectos where id=900101;"
caso "la marca de sesión sola no autoconfirma a una cuenta del equipo" "true" gerente_tmk "$CITADO" "select set_config('kux.confirmando','si',true); update funnel_prospectos set cita_confirmada_en=now() where id=900101; $DUE select (cita_confirmada_en is null)::text from funnel_prospectos where id=900101;"
caso "anónimo sin permiso sobre lugares" "false" _dueno "" "select has_table_privilege('anon','public.funnel_restaurantes','select')::text;"
LLEGO="$CITADO update funnel_prospectos set recepcion_en=now() where id=900101;"
caso "ya llegó a la sala: no se regresa" "ERROR: este cliente ya llegó a la sala: lo ve Recepción" supervisor_tmk "$LLEGO" "$REG(900101,'x');"
caso "ya llegó a la sala: el telemarketer no lo mueve" "ERROR: este cliente ya llegó a la sala: lo ve Recepción" telemarketing "$LLEGO" "$RES(900101,'no_interesado',false);"
caso "ya llegó a la sala: sale de la lista de citas" "0" supervisor_tmk "$LLEGO" "select count(*) from funnel_citas_lista() where id=900101;"
caso "ronda 2: supervisor cita DIRECTO en la tabla fuera de horario: frena" "ERROR: ese día y hora no es un horario del lugar" supervisor_tmk "$ATAR $HOR" "update funnel_prospectos set estado='asistira', restaurante_id=$REST1, presenta_en=$CUANDO+interval '37 minutes' where id=900102;"
caso "ronda 2: supervisor cita DIRECTO en la tabla en un horario lleno: frena" "ERROR: ese horario ya está lleno" supervisor_tmk "$ATAR $HOR update funnel_prospectos set estado='asistira', restaurante_id=$REST1, presenta_en=$CUANDO where id in (900101,900103);" "update funnel_prospectos set estado='asistira', restaurante_id=$REST1, presenta_en=$CUANDO where id=900102;"
caso "ronda 2: con la marca de sesión, otra función NO conserva la confirmación" "false" telemarketing "$CITADO" "$DUE select set_config('request.jwt.claims', '{\"role\":\"authenticated\",\"app_metadata\":{\"role\":\"admin\"},\"email\":\"admin@prueba.kx\"}', true); select funnel_cita_confirmar(900101,$REST1,$CUANDO,true,false); select set_config('request.jwt.claims', '$(claims telemarketing)', true); set local role authenticated; select set_config('kux.confirmando','si',true); $RES(900101,'no_interesado',false); $DUE select (cita_confirmada_en is not null)::text from funnel_prospectos where id=900101;"
caso "ronda 2: un telemarketer con el permiso igual no confirma" "ERROR: no autorizado" telemarketing "$CITADO update funnel_permisos set permitido=true where rol_clave='telemarketing' and permiso='confirmar_citas';" "$CONF(900101,$REST1,$CUANDO,false,false);"
caso "anónimo no confirma ni lista" "false|false" _dueno "" "select has_function_privilege('anon','public.funnel_cita_confirmar(bigint,bigint,timestamptz,boolean,boolean)','execute')::text||'|'||has_function_privilege('anon','public.funnel_citas_lista()','execute')::text;"

echo "· bloque 4: la sala (hostess, liner, closer por turno)"
REST2="(select min(id) from funnel_restaurantes where activo and id>$REST1)"
HOY_GT="((now() at time zone 'America/Guatemala')::date)"
A_LAS="(($HOY_GT + time '12:00') at time zone 'America/Guatemala')"
SALA="insert into auth.users(id,email,raw_app_meta_data) values (md5('kx-recepcion')::uuid,'recepcion@prueba.kx','{\"role\":\"recepcion\"}'),(md5('kx-vendedor')::uuid,'vendedor@prueba.kx','{\"role\":\"vendedor\"}') on conflict (id) do nothing;
 insert into funnel_agentes(id,nombre,rol,email,activo,peso,user_id) overriding system value values
  (900011,'H1','recepcion','recepcion@prueba.kx',true,1,md5('kx-recepcion')::uuid),(900012,'H2','recepcion','h2@prueba.kx',true,1,null),
  (900021,'L1','vendedor','vendedor@prueba.kx',true,1,md5('kx-vendedor')::uuid),(900022,'L2','vendedor','l2@prueba.kx',true,1,null),
  (900031,'C1','cerrador','c1@prueba.kx',true,1,null),(900032,'C2','cerrador','c2@prueba.kx',true,1,null),(900033,'C3','cerrador','c3@prueba.kx',true,1,null);
 insert into funnel_turnos(id,fecha,restaurante_id,agente_id) overriding system value values
  (900401,$HOY_GT,$REST1,900011),(900402,$HOY_GT,$REST2,900012),(900403,$HOY_GT,$REST1,900021),(900404,$HOY_GT,$REST1,900022),
  (900405,$HOY_GT,$REST1,900031),(900406,$HOY_GT,$REST1,900032);
 select set_config('kux.confirmando','si',true);
 update funnel_prospectos set estado='asistira', etapa='telemarketing', restaurante_id=$REST1, presenta_en=$A_LAS, cita_confirmada_en=now() where id in (900101,900104);
 update funnel_prospectos set estado='asistira', etapa='telemarketing', restaurante_id=$REST2, presenta_en=$A_LAS, cita_confirmada_en=now() where id=900102;
 update funnel_prospectos set estado='asistira', etapa='telemarketing', restaurante_id=$REST1, presenta_en=$A_LAS+interval '1 day', cita_confirmada_en=now() where id=900103;
 select set_config('kux.confirmando','',true);
 update funnel_prospectos set estado='asistira', etapa='telemarketing', restaurante_id=$REST1, presenta_en=$A_LAS where id=900105;"
CAL="select funnel_sala_calificar"
ASG="select funnel_sala_asignar"
EN_SALA="$SALA select set_config('request.jwt.claims','{\"role\":\"authenticated\",\"app_metadata\":{\"role\":\"admin\"},\"email\":\"admin@prueba.kx\"}',true); select funnel_sala_calificar(900101,true,40,'casado',2,'Visa',null);"
caso "la hostess ve SOLO las citas confirmadas de hoy de SU lugar" "pA,pX" recepcion "$SALA" "select string_agg(nombre,',' order by nombre) from funnel_sala_hoy();"
caso "la hostess sin turno hoy no ve nada" "0" recepcion "$SALA delete from funnel_turnos where agente_id=900011;" "select count(*) from funnel_sala_hoy();"
caso "la hostess con la matriz apagada no entra" "ERROR: no autorizado" recepcion "$SALA update funnel_permisos set permitido=false where rol_clave='recepcion' and permiso='recibir_sala';" "select count(*) from funnel_sala_hoy();"
caso "la hostess ya no lee la tabla directo" "0" recepcion "$SALA" "select count(*) from funnel_prospectos;"
caso "la hostess ya no escribe la tabla directo" "0" recepcion "$SALA" "with u as (update funnel_prospectos set vendedor_id=900021 returning 1) select count(*) from u;"
caso "la hostess ya no ve contratos ni reservas" "0|0" recepcion "$SALA" "select (select count(*) from funnel_contratos)||'|'||(select count(*) from funnel_reservas);"
caso "gerencia de ventas ve todos los lugares de hoy" "pA,pB,pX" gerente_ventas "$SALA" "select string_agg(nombre,',' order by nombre) from funnel_sala_hoy();"
caso "tmk no ve la sala" "ERROR: no autorizado" telemarketing "$SALA" "select count(*) from funnel_sala_hoy();"
caso "llegada: queda anotada" "true" recepcion "$SALA" "select funnel_sala_llegada(900101); $DUE select (recepcion_en is not null)::text from funnel_prospectos where id=900101;"
caso "llegada en OTRO lugar: frena" "ERROR: no autorizado" recepcion "$SALA" "select funnel_sala_llegada(900102);"
caso "llegada de una cita de MAÑANA: frena" "ERROR: no autorizado" recepcion "$SALA" "select funnel_sala_llegada(900103);"
caso "llegada de una cita SIN confirmar: frena" "ERROR: no autorizado" recepcion "$SALA" "select funnel_sala_llegada(900105);"
caso "califica → la rueda le da el primer liner" "sala|900021" recepcion "$SALA" "$CAL(900101,true,40,'casado',2,'Visa',null); $DUE select etapa||'|'||vendedor_id from funnel_prospectos where id=900101;"
caso "rueda pareja: dos clientes → dos liners distintos" "900021,900022" recepcion "$SALA" "$CAL(900101,true); $CAL(900104,true); $DUE select string_agg(vendedor_id::text,',' order by vendedor_id) from funnel_prospectos where id in (900101,900104);"
caso "rueda: el liner que salió a comer se salta" "900022" recepcion "$SALA update funnel_turnos set disponible=false where id=900403;" "$CAL(900101,true); $DUE select vendedor_id from funnel_prospectos where id=900101;"
caso "sin liner en turno: califica igual y AVISA" "sala|null|true" recepcion "$SALA delete from funnel_turnos where agente_id in (900021,900022);" "select set_config('kx.aviso',funnel_sala_calificar(900101,true)->>'aviso',true); $DUE select etapa||'|'||coalesce(vendedor_id::text,'null')||'|'||(current_setting('kx.aviso') ilike '%no hay ningún liner%')::text from funnel_prospectos where id=900101;"
caso "no califica sin motivo: frena" "ERROR: escribí por qué no califica" recepcion "$SALA" "$CAL(900101,false);"
caso "no califica con motivo: baja y sin liner" "baja|null" recepcion "$SALA" "$CAL(900101,false,null,null,null,null,'sin tarjeta'); $DUE select etapa||'|'||coalesce(vendedor_id::text,'null') from funnel_prospectos where id=900101;"
caso "edad absurda: frena" "ERROR: la edad no cuadra (18 a 110)" recepcion "$SALA" "$CAL(900101,true,7);"
caso "pasar a closer: la rueda le da el primer closer" "900031" recepcion "$EN_SALA" "$ASG(900101,'cerrador'); $DUE select cerrador_id from funnel_prospectos where id=900101;"
caso "closer antes de calificar: frena" "ERROR: primero tiene que calificar" recepcion "$SALA" "$ASG(900101,'cerrador');"
caso "sin liner no hay closer" "ERROR: primero el liner" recepcion "$SALA delete from funnel_turnos where agente_id in (900021,900022);" "$CAL(900101,true); $ASG(900101,'cerrador');"
caso "sin closer en turno: avisa, no se calla" "ERROR: no hay ningún closer disponible en turno hoy en este lugar: pedile al gerente que arme el turno" recepcion "$EN_SALA delete from funnel_turnos where agente_id in (900031,900032);" "$ASG(900101,'cerrador');"
caso "el liner asignado lo pasa a closer" "900031" vendedor "$EN_SALA" "$ASG(900101,'cerrador'); $DUE select cerrador_id from funnel_prospectos where id=900101;"
caso "el liner NO asignado no lo pasa" "ERROR: no autorizado" vendedor "$EN_SALA update funnel_prospectos set vendedor_id=900022 where id=900101;" "$ASG(900101,'cerrador');"
caso "el liner no elige closer a mano" "ERROR: no autorizado" vendedor "$EN_SALA" "$ASG(900101,'cerrador',900032);"
caso "a mano: la hostess cambia a otro closer en turno (queda anotado)" "900032|manual|recepcion@prueba.kx" recepcion "$EN_SALA" "$ASG(900101,'cerrador',900032); $DUE select agente_id||'|'||modo||'|'||actor from funnel_sala_asignaciones where prospecto_id=900101 and rol='cerrador';"
caso "a mano a alguien FUERA de turno: frena" "ERROR: esa persona no está en turno hoy como closer en este lugar" recepcion "$EN_SALA" "$ASG(900101,'cerrador',900033);"
caso "a mano con un liner en el puesto de closer: frena" "ERROR: esa persona no está en turno hoy como closer en este lugar" recepcion "$EN_SALA" "$ASG(900101,'cerrador',900022);"
caso "con uno solo en turno, «siguiente» dice que no hay OTRO (no que falta el turno)" "ERROR: no hay otro closer disponible en turno hoy en este lugar" recepcion "$EN_SALA delete from funnel_turnos where agente_id=900032;" "$ASG(900101,'cerrador'); $ASG(900101,'cerrador');"
echo "· bloque 4 · ronda 1 ciber: la sala es vinculante"
CON_CLOSER="$EN_SALA select funnel_sala_asignar(900101,'cerrador');"
caso "ciber #1: el liner no se pone liner/closer directo en la tabla" "ERROR: eso se anota desde Recepción, no directo en la tabla" vendedor "$EN_SALA" "update funnel_prospectos set cerrador_id=900033 where id=900101;"
caso "ciber #1: ni gerencia cambia el closer directo en la tabla" "ERROR: eso se anota desde Recepción, no directo en la tabla" gerente_ventas "$EN_SALA" "update funnel_prospectos set cerrador_id=900032 where id=900101;"
caso "ciber #1: nadie pasa a sala directo en la tabla" "ERROR: eso se anota desde Recepción, no directo en la tabla" gerente_ventas "$SALA" "update funnel_prospectos set etapa='sala', califica=true where id=900101;"
caso "ciber #1: nadie da de alta un prospecto ya en sala" "ERROR: eso se anota desde Recepción, no directo en la tabla" gerente_ventas "" "insert into funnel_prospectos(nombre,etapa,vendedor_id) values ('x','sala',900021);"
caso "gerencia sí da de baja desde la sala (postventa/baja sigue andando)" "1" gerente_ventas "$EN_SALA" "with u as (update funnel_prospectos set etapa='baja', motivo_baja='x' where id=900101 returning 1) select count(*) from u;"
caso "gerencia sí carga una base (alta normal)" "1" gerente_ventas "" "with i as (insert into funnel_prospectos(nombre) values ('nuevo') returning 1) select count(*) from i;"
caso "ciber #2: el liner no inserta contratos directo" "ERROR" vendedor "$EN_SALA" "insert into funnel_contratos(prospecto_id,tipo_membresia,plan_pago,monto,vendedor_id,cerrador_id,estado) values (900101,'x','y',99999,900021,900033,'firmado');"
caso "ciber #2: nadie borra contratos directo" "ERROR" gerente_ventas "" "delete from funnel_contratos;"
caso "ciber #2: al cerrar, el closer es el que asignó la sala" "ERROR: el liner y el closer del contrato son los que asignó la sala" vendedor "$CON_CLOSER" "select funnel_cerrar_contrato(900101,'x','y',900021,900033,null,4);"
caso "ciber #2: al cerrar con el closer de la sala, entra" "socio|900021|900031" vendedor "$CON_CLOSER insert into funnel_membresias(tipo,precio) select 'x',1000 where not exists (select 1 from funnel_membresias where tipo='x');" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4); $DUE select etapa||'|'||vendedor_id||'|'||cerrador_id from funnel_prospectos where id=900101;"
caso "ciber #3: el liner no vuelve a tirar la rueda para elegir closer" "ERROR: no autorizado" vendedor "$CON_CLOSER" "$ASG(900101,'cerrador');"
caso "ciber #3: el liner no pide closer para una cita sin confirmar" "ERROR: no autorizado" vendedor "$EN_SALA select set_config('kux.confirmando','si',true); update funnel_prospectos set cita_confirmada_en=null where id=900101; select set_config('kux.confirmando','',true);" "$ASG(900101,'cerrador');"
caso "ciber #3: la rueda cuenta los clientes que TIENE (el que se lo quitaron vuelve a recibir)" "900021" recepcion "$EN_SALA" "$ASG(900101,'vendedor',900022); $CAL(900104,true); $DUE select vendedor_id from funnel_prospectos where id=900104;"
caso "ciber #4: la bitácora no acepta 'contrato' del cliente" "ERROR" vendedor "$EN_SALA" "insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900101,'contrato','vendedor@prueba.kx','{}');"
caso "ciber #4: ni un tipo reservado con un espacio invisible" "ERROR" vendedor "$EN_SALA" "insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900101,'sala_asignado'||chr(8203),'vendedor@prueba.kx','{}');"
caso "ciber #4: lo de la lista blanca sí entra (contacto)" "1" vendedor "$EN_SALA" "with i as (insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900101,'contacto','vendedor@prueba.kx','{}') returning 1) select count(*) from i;"
caso "ciber #5: la hostess no vuelve a la tabla por el organigrama" "0" recepcion "$SALA update funnel_agentes set supervisor_id=900011 where id=900002;" "select count(*) from funnel_prospectos;"
echo "· bloque 4 · ronda 2 ciber: el cierre respeta la sala"
MEMB="insert into funnel_membresias(tipo,precio) select 'x',1000 where not exists (select 1 from funnel_membresias where tipo='x');"
caso "ciber2 A1: sacarlo de sala por la tabla no se puede" "ERROR: eso se anota desde Recepción, no directo en la tabla" vendedor "$CON_CLOSER" "update funnel_prospectos set etapa='presentacion' where id=900101;"
caso "ciber2 A1b: dado de baja no se cierra (liner)" "ERROR: solo se cierra a quien calificó en la sala" vendedor "$CON_CLOSER $MEMB" "update funnel_prospectos set etapa='baja' where id=900101; select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4);"
caso "ciber2 A2: antes de calificar no se cierra" "ERROR: solo se cierra a quien calificó en la sala" vendedor "$SALA $MEMB" "select funnel_cerrar_contrato(900101,'x','y',900021,900033,null,4);"
caso "ciber2 C3: sin closer no se cierra" "ERROR: falta el closer: pasalo a closer en Recepción" vendedor "$EN_SALA $MEMB" "select funnel_cerrar_contrato(900101,'x','y',900021,null,null,4);"
caso "ciber2 C4: quien llegó no se esconde de Recepción cambiando el estado" "ERROR: eso se anota desde Recepción, no directo en la tabla" vendedor "$EN_SALA" "update funnel_prospectos set estado='interesado' where id=900101;"
caso "ciber2 5: ni gerencia lo mueve de lugar en dos pasos" "ERROR: eso se anota desde Recepción, no directo en la tabla" gerente_ventas "$EN_SALA" "update funnel_prospectos set etapa='presentacion' where id=900101;"
caso "ciber2: gerencia SÍ da de baja a quien llegó" "1" gerente_ventas "$SALA select set_config('request.jwt.claims','{\"role\":\"authenticated\",\"app_metadata\":{\"role\":\"admin\"},\"email\":\"admin@prueba.kx\"}',true); select funnel_sala_llegada(900101);" "with u as (update funnel_prospectos set etapa='baja', motivo_baja='x' where id=900101 returning 1) select count(*) from u;"
echo "· bloque 4 · ronda 3 ciber: las comisiones no se desvían por la tabla"
caso "ciber3 #1: el liner no cambia el telemarketer" "ERROR: eso no se cambia directo en la tabla" vendedor "$CON_CLOSER" "update funnel_prospectos set tmk_id=900004 where id=900101;"
caso "ciber3 #1: ni gerencia cambia el telemarketer de quien ya llegó" "ERROR: eso no se cambia directo en la tabla" gerente_ventas "$EN_SALA" "update funnel_prospectos set tmk_id=900004 where id=900101;"
caso "ciber3 #1: gerencia sí reparte a quien no llegó" "1" gerente_tmk "" "with u as (update funnel_prospectos set tmk_id=900003 where id=900105 returning 1) select count(*) from u;"
caso "ciber3 #2: nadie cuelga el prospecto de un socio ajeno" "ERROR: eso no se cambia directo en la tabla" gerente_ventas "$CON_CLOSER" "update funnel_prospectos set socio_id=(select min(id) from socios) where id=900101;"
caso "ciber3 #2: ni lo da de alta ya colgado de un socio" "ERROR: eso se anota desde Recepción, no directo en la tabla" gerente_ventas "" "insert into funnel_prospectos(nombre,socio_id) values ('x',(select min(id) from socios));"
echo "· bloque 4 · George 19-sep: solo gerencia de ventas corrige la sala al cerrar"
caso "gerente de TMK NO cierra con otro closer" "ERROR: el liner y el closer del contrato son los que asignó la sala" gerente_tmk "$CON_CLOSER $MEMB" "select funnel_cerrar_contrato(900101,'x','y',900021,900032,null,4);"
caso "supervisor de TMK NO cierra antes de calificar" "ERROR: solo se cierra a quien calificó en la sala" supervisor_tmk "$SALA $MEMB" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4);"
caso "gerente de ventas SÍ corrige el closer al cerrar" "socio|900032" gerente_ventas "$CON_CLOSER $MEMB" "select funnel_cerrar_contrato(900101,'x','y',900021,900032,null,4); $DUE select etapa||'|'||cerrador_id from funnel_prospectos where id=900101;"
caso "corregir_sala solo en admin, gerente general y de ventas" "admin,gerente_general,gerente_ventas" _dueno "" "select string_agg(rol_clave,',' order by rol_clave) from funnel_permisos where permiso='corregir_sala' and permitido;"
echo "· bloque 4 · ronda 1 QA: la rueda cuenta bien"
# L1 «recibió» 2 hoy pero ya no los tiene; L2 tiene 1 de verdad → la rueda le toca a L1 (contar filas crudas daría L2).
CRUDO="$SALA update funnel_prospectos set vendedor_id=900022 where id=900104;
 insert into funnel_sala_asignaciones(prospecto_id,rol,agente_id,modo) values (900102,'vendedor',900021,'rueda'),(900103,'vendedor',900021,'rueda'),(900104,'vendedor',900022,'rueda');"
caso "QA M1: la rueda cuenta los que TIENE hoy, no las filas" "900021" recepcion "$CRUDO" "$CAL(900101,true); $DUE select vendedor_id from funnel_prospectos where id=900101;"
caso "QA M1: el turno muestra los que TIENE hoy" "0,1" recepcion "$CRUDO" "select string_agg(clientes_hoy::text,',' order by agente_id) from funnel_turnos_dia() where rol='vendedor';"
# Empate en clientes: le toca al que lleva MÁS rato sin recibir (L2 recibió hace 3 h, L1 hace 1 h).
EMPATE="$SALA update funnel_prospectos set vendedor_id=900021 where id=900102; update funnel_prospectos set vendedor_id=900022 where id=900103;
 insert into funnel_sala_asignaciones(prospecto_id,rol,agente_id,modo,creado_en) values (900102,'vendedor',900021,'rueda',now()-interval '1 hour'),(900103,'vendedor',900022,'rueda',now()-interval '3 hours');"
caso "QA A3: empate → el que lleva más rato sin recibir" "900022" recepcion "$EMPATE" "$CAL(900101,true); $DUE select vendedor_id from funnel_prospectos where id=900101;"
# Lo de AYER en Guatemala no cuenta hoy, aunque la sesión esté en UTC (22:00 y 23:00 de ayer en GT = hoy en UTC).
AYER="$SALA set local timezone='UTC'; update funnel_prospectos set vendedor_id=900021 where id in (900102,900103);
 insert into funnel_sala_asignaciones(prospecto_id,rol,agente_id,modo,creado_en) values
  (900102,'vendedor',900021,'rueda',((((now() at time zone 'America/Guatemala')::date - 1) + time '22:00') at time zone 'America/Guatemala')),
  (900103,'vendedor',900021,'rueda',((((now() at time zone 'America/Guatemala')::date - 1) + time '23:00') at time zone 'America/Guatemala'));
 update funnel_prospectos set vendedor_id=900022 where id=900104; insert into funnel_sala_asignaciones(prospecto_id,rol,agente_id,modo) values (900104,'vendedor',900022,'rueda');"
caso "QA A3: lo de ayer (hora de Guatemala) no cuenta hoy, con la sesión en UTC" "900021" recepcion "$AYER" "$CAL(900101,true); $DUE select vendedor_id from funnel_prospectos where id=900101;"
caso "QA M2: una pantalla vieja no pisa lo que otra persona ya cambió" "ERROR: otra persona ya lo cambió: tocá Actualizar" recepcion "$EN_SALA" "select funnel_sala_asignar(900101,'vendedor',null,0);"
caso "QA M2: con lo que ve la pantalla al día, sí cambia" "900022" recepcion "$EN_SALA" "select funnel_sala_asignar(900101,'vendedor',null,900021); $DUE select vendedor_id from funnel_prospectos where id=900101;"
caso "QA M6: ya en sala, nadie lo mueve de lugar por la tabla" "ERROR: eso se anota desde Recepción, no directo en la tabla" gerente_ventas "$EN_SALA" "update funnel_prospectos set restaurante_id=$REST2 where id=900101;"
caso "la rueda tiene candado por lugar y rol" "true" _dueno "" "select (pg_get_functiondef('public.funnel_sala_rueda(bigint,text,bigint)'::regprocedure) ilike '%pg_advisory_xact_lock%')::text;"
caso "nadie escribe asignaciones directo (ni gerencia)" "ERROR" gerente_ventas "$SALA" "insert into funnel_sala_asignaciones(prospecto_id,rol,agente_id,modo) values (900101,'vendedor',900021,'rueda');"
caso "nadie escribe turnos directo (ni gerencia)" "ERROR" gerente_ventas "$SALA" "insert into funnel_turnos(fecha,restaurante_id,agente_id) values (current_date,$REST1,900033);"
caso "la bitácora de la sala no se falsifica" "ERROR" gerente_tmk "" "insert into funnel_eventos(prospecto_id,tipo,actor,payload) values (900101,'sala_asignado','gerente_tmk@prueba.kx','{}');"
caso "la hostess no arma turnos" "ERROR: no autorizado" recepcion "$SALA" "select funnel_turno_poner($HOY_GT,$REST1,900033);"
caso "el supervisor de ventas arma el turno" "1" supervisor "$SALA" "select funnel_turno_poner($HOY_GT,$REST1,900033); $DUE select count(*) from funnel_turnos where agente_id=900033;"
caso "turno en una fecha que ya pasó: frena" "ERROR: esa fecha ya pasó" supervisor "$SALA" "select funnel_turno_poner($HOY_GT-1,$REST1,900033);"
caso "turno a un telemarketer: frena" "ERROR: esa persona no es hostess, liner ni closer activo" supervisor "$SALA" "select funnel_turno_poner($HOY_GT,$REST1,900002);"
caso "una persona, un lugar por día (se mueve, no se duplica)" "1" supervisor "$SALA" "select funnel_turno_poner($HOY_GT,$REST2,900021); $DUE select count(*) from funnel_turnos where agente_id=900021;"
caso "la hostess pausa a un liner de SU sala" "false" recepcion "$SALA" "select funnel_turno_disponible(900403,false); $DUE select disponible::text from funnel_turnos where id=900403;"
caso "la hostess NO pausa a alguien de otra sala" "ERROR: no autorizado" recepcion "$SALA" "select funnel_turno_disponible(900402,false);"
caso "la hostess ve el turno de su sala, no el de otra" "5" recepcion "$SALA" "select count(*) from funnel_turnos_dia();"
caso "tmk no ve turnos" "ERROR: no autorizado" telemarketing "$SALA" "select count(*) from funnel_turnos_dia();"
caso "la rueda y la toma no se llaman desde afuera" "false|false" _dueno "" "select has_function_privilege('authenticated','public.funnel_sala_rueda(bigint,text,bigint)','execute')::text||'|'||has_function_privilege('authenticated','public.funnel_sala_tomar(bigint)','execute')::text;"
caso "anónimo no toca la sala" "false|false|false" _dueno "" "select has_function_privilege('anon','public.funnel_sala_hoy()','execute')::text||'|'||has_function_privilege('anon','public.funnel_sala_calificar(bigint,boolean,integer,text,integer,text,text)','execute')::text||'|'||has_function_privilege('anon','public.funnel_turno_poner(date,bigint,bigint)','execute')::text;"

echo "· bloque 5: descuentos por segmento, aprobación y verificación"
ADM5="select set_config('request.jwt.claims','{\"role\":\"authenticated\",\"app_metadata\":{\"role\":\"admin\"},\"email\":\"admin@prueba.kx\"}',true);"
SEG="$MEMB insert into funnel_descuentos(id,nombre,tipo,valor,membresias,activo) overriding system value values
 (900501,'Contado','porcentaje',10,null,true),(900502,'Referido','monto',100,array['VIP'],true),(900503,'Apagado','porcentaje',5,null,false);
 insert into auth.users(id,email,raw_app_meta_data) values (md5('kx-verificador')::uuid,'verificador@prueba.kx','{\"role\":\"verificador\"}') on conflict (id) do nothing;
 insert into funnel_agentes(id,nombre,rol,email,activo,peso,user_id) overriding system value values (900041,'V1','verificador','verificador@prueba.kx',true,1,md5('kx-verificador')::uuid);"
PEDIDO="$CON_CLOSER $SEG $ADM5 select funnel_descuento_pedir(900101,'x',900501); select set_config('kx.sol',(select max(id)::text from funnel_descuento_solicitudes),true);"
APROBADO="$PEDIDO update funnel_descuento_solicitudes set estado='aprobada' where prospecto_id=900101 and estado='pendiente';"
CERRADO="$CON_CLOSER $SEG $ADM5 select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4);"
CID="(select id from funnel_contratos where prospecto_id=900101)"
VER="select funnel_contrato_verificar"
caso "el liner pide un 10 %: 100 de descuento, queda en 900" "100.00|900.00" vendedor "$CON_CLOSER $SEG" "select (r->>'monto_descuento')||'|'||(r->>'precio_final') from (select funnel_descuento_pedir(900101,'x',900501) r) x;"
caso "segmento que no aplica a esa membresía: frena" "ERROR: ese segmento no aplica a la membresía x" vendedor "$CON_CLOSER $SEG" "select funnel_descuento_pedir(900101,'x',900502);"
caso "segmento apagado: frena" "ERROR: ese segmento de descuento no existe o está apagado" vendedor "$CON_CLOSER $SEG" "select funnel_descuento_pedir(900101,'x',900503);"
caso "telemarketing no pide descuentos" "ERROR: no autorizado" telemarketing "$CON_CLOSER $SEG" "select funnel_descuento_pedir(900101,'x',900501);"
caso "un liner que no es el del cliente no pide" "ERROR: no autorizado" vendedor "$CON_CLOSER $SEG update funnel_prospectos set vendedor_id=900022 where id=900101;" "select funnel_descuento_pedir(900101,'x',900501);"
caso "con el descuento pendiente no se cierra" "ERROR: el descuento todavía no está aprobado por el gerente de ventas" vendedor "$PEDIDO" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4,current_setting('kx.sol')::bigint);"
caso "el liner no aprueba descuentos" "ERROR: no autorizado" vendedor "$PEDIDO" "select funnel_descuento_resolver(current_setting('kx.sol')::bigint,true);"
caso "el supervisor de ventas no aprueba descuentos" "ERROR: no autorizado" supervisor "$PEDIDO" "select funnel_descuento_resolver(current_setting('kx.sol')::bigint,true);"
caso "el gerente de ventas ve el pedido por aprobar" "1" gerente_ventas "$PEDIDO" "select count(*) from funnel_descuentos_por_aprobar() where prospecto_id=900101;"
caso "rechazar sin motivo: frena" "ERROR: escribí por qué lo rechazás" gerente_ventas "$PEDIDO" "select funnel_descuento_resolver(current_setting('kx.sol')::bigint,false);"
caso "rechazado: no se cierra con ese descuento" "ERROR: el descuento todavía no está aprobado por el gerente de ventas" vendedor "$PEDIDO update funnel_descuento_solicitudes set estado='rechazada';" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4,current_setting('kx.sol')::bigint);"
caso "aprobado: cierra en 900, por verificar, comisiones pendientes" "900|por_verificar|pendiente" vendedor "$APROBADO" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4,current_setting('kx.sol')::bigint); $DUE select c.monto::int||'|'||c.estado||'|'||string_agg(distinct m.estado,',') from funnel_contratos c join funnel_comisiones m on m.contrato_id=c.id where c.prospecto_id=900101 group by c.monto,c.estado;"
caso "el descuento aprobado se usa UNA vez" "usada" vendedor "$APROBADO" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4,current_setting('kx.sol')::bigint); $DUE select estado from funnel_descuento_solicitudes where id=current_setting('kx.sol')::bigint;"
caso "aprobado para otra membresía: frena" "ERROR: el descuento se aprobó para la membresía x" vendedor "$APROBADO insert into funnel_membresias(tipo,precio) values ('z',2000);" "select funnel_cerrar_contrato(900101,'z','y',900021,900031,null,4,current_setting('kx.sol')::bigint);"
caso "descuento de otro cliente: frena" "ERROR: ese descuento no es de este cliente" gerente_ventas "$APROBADO update funnel_descuento_solicitudes set prospecto_id=900102;" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4,current_setting('kx.sol')::bigint);"
caso "sin descuento: precio de lista − descuento de la membresía" "950" vendedor "$CON_CLOSER $SEG update funnel_membresias set descuento=50 where tipo='x';" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4); $DUE select monto::int from funnel_contratos where prospecto_id=900101;"
caso "el monto ya no lo escribe nadie (la función no lo recibe)" "0" _dueno "" "select count(*) from pg_proc where proname='funnel_cerrar_contrato' and 'p_monto'=any(proargnames);"
caso "membresía inexistente o apagada: frena" "ERROR: elegí una membresía activa" vendedor "$CON_CLOSER $SEG" "select funnel_cerrar_contrato(900101,'nada','y',900021,900031,null,4);"
caso "el gerente de ventas crea segmentos" "1" gerente_ventas "" "with i as (insert into funnel_descuentos(nombre,tipo,valor) values ('Aniversario','porcentaje',15) returning 1) select count(*) from i;"
caso "el liner no crea segmentos" "ERROR" vendedor "" "insert into funnel_descuentos(nombre,tipo,valor) values ('Mío','porcentaje',90);"
caso "un segmento de más de 100 % no existe" "ERROR" gerente_ventas "" "insert into funnel_descuentos(nombre,tipo,valor) values ('Todo','porcentaje',150);"
caso "nadie borra segmentos" "ERROR" gerente_ventas "$SEG" "delete from funnel_descuentos where id=900501;"
caso "nadie cambia el valor de un segmento (solo apagarlo)" "ERROR" gerente_ventas "$SEG" "update funnel_descuentos set valor=99 where id=900501;"
caso "pedidos de descuento: nadie los toca directo" "ERROR" gerente_ventas "$PEDIDO" "update funnel_descuento_solicitudes set estado='aprobada';"
caso "el verificador ve el contrato por verificar" "1" verificador "$CERRADO" "select count(*) from funnel_contratos_por_verificar() where cliente='pA';"
caso "el liner no verifica" "ERROR: no autorizado" vendedor "$CERRADO" "$VER($CID,'verificado');"
caso "verificado: comisiones liberadas + la del verificador a su nombre" "verificado|liberada|900041" verificador "$CERRADO" "$VER($CID,'verificado'); $DUE select c.estado||'|'||string_agg(distinct m.estado,',')||'|'||max(case when m.rol='verificador' then m.beneficiario_id end) from funnel_contratos c join funnel_comisiones m on m.contrato_id=c.id where c.prospecto_id=900101 group by c.estado;"
caso "con observaciones sin nota: frena" "ERROR: escribí qué pasó con el cliente" verificador "$CERRADO" "$VER($CID,'observado');"
caso "observado y después verificado" "verificado" verificador "$CERRADO" "$VER($CID,'observado','no contestó'); $VER($CID,'verificado'); $DUE select estado from funnel_contratos where prospecto_id=900101;"
caso "se arrepintió: contrato cancelado, comisiones anuladas, baja, socio marcado" "cancelado|anulada|baja|true" verificador "$CERRADO" "$VER($CID,'arrepentido','no quiere seguir'); $DUE select c.estado||'|'||string_agg(distinct m.estado,',')||'|'||p.etapa||'|'||(s.contrato_cancelado_en is not null)::text from funnel_contratos c join funnel_comisiones m on m.contrato_id=c.id join funnel_prospectos p on p.id=c.prospecto_id join socios s on s.id=c.socio_id where c.prospecto_id=900101 group by c.estado,p.etapa,s.contrato_cancelado_en;"
caso "el socio no se borra al arrepentirse" "1" verificador "$CERRADO" "$VER($CID,'arrepentido','x'); $DUE select count(*) from socios where id=(select socio_id from funnel_contratos where prospecto_id=900101);"
caso "ya verificado: no se vuelve a verificar" "ERROR: ese contrato ya no está por verificar" verificador "$CERRADO" "$VER($CID,'verificado'); $VER($CID,'arrepentido','x');"
caso "nadie verifica una venta en la que participó" "ERROR: no podés verificar una venta en la que participaste" verificador "$CON_CLOSER $SEG update funnel_prospectos set tmk_id=900041 where id=900101; $ADM5 select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4);" "$VER($CID,'verificado');"
caso "comisiones: nadie las libera directo" "ERROR" gerente_ventas "$CERRADO" "update funnel_comisiones set estado='liberada';"
caso "anónimo no toca descuentos ni verificación" "false|false|false" _dueno "" "select has_function_privilege('anon','public.funnel_descuento_pedir(bigint,text,bigint)','execute')::text||'|'||has_function_privilege('anon','public.funnel_contrato_verificar(bigint,text,text)','execute')::text||'|'||has_function_privilege('anon','public.funnel_cerrar_contrato(bigint,text,text,bigint,bigint,bigint,integer,bigint)','execute')::text;"
caso "el closer retira su pedido pendiente y cierra sin descuento" "1000" vendedor "$PEDIDO" "select funnel_descuento_retirar(900101); select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4); $DUE select monto::int from funnel_contratos where prospecto_id=900101;"
caso "un liner ajeno no retira el pedido" "ERROR: no autorizado" vendedor "$PEDIDO update funnel_prospectos set vendedor_id=900022 where id=900101;" "select funnel_descuento_retirar(900101);"
echo "· bloque 5 · ronda 1 (ciber + QA)"
caso "ciber H1: un supervisor (es gerente) no toca el precio de la membresía" "0" supervisor "$SEG" "with u as (update funnel_membresias set descuento=precio where tipo='x' returning 1) select count(*) from u;"
caso "ciber H1: gerente de TMK tampoco" "0" gerente_tmk "$SEG" "with u as (update funnel_membresias set precio=1 where tipo='x' returning 1) select count(*) from u;"
caso "ciber H1: el gerente de ventas sí" "1" gerente_ventas "$SEG" "with u as (update funnel_membresias set precio=1100 where tipo='x' returning 1) select count(*) from u;"
caso "ciber H1: descuento de membresía negativo: no existe" "ERROR" gerente_ventas "$SEG" "update funnel_membresias set descuento=-9000 where tipo='x';"
caso "ciber H1: precio vacío: no existe" "ERROR" gerente_ventas "$SEG" "update funnel_membresias set precio=null where tipo='x';"
caso "ciber H4: segmento NaN: no existe" "ERROR" gerente_ventas "" "insert into funnel_descuentos(nombre,tipo,valor) values ('n','monto','NaN');"
caso "ciber H5: creado_por no se falsifica" "ERROR" gerente_ventas "" "insert into funnel_descuentos(nombre,tipo,valor,creado_por) values ('n','monto',5,'george@kuxtal.app');"
caso "ciber H5: creado_por lo pone la base" "gerente_ventas@prueba.kx" gerente_ventas "" "insert into funnel_descuentos(nombre,tipo,valor) values ('n','monto',5); $DUE select creado_por from funnel_descuentos where nombre='n';"
caso "QA M1: un descuento que deja el precio en 0: frena" "ERROR: ese descuento deja el precio en 0: no se puede" vendedor "$CON_CLOSER $SEG insert into funnel_descuentos(id,nombre,tipo,valor) overriding system value values (900504,'todo','monto',1000);" "select funnel_descuento_pedir(900101,'x',900504);"
caso "ciber H2: nadie aprueba su propio pedido" "ERROR: no podés aprobar tu propio pedido de descuento" admin "$PEDIDO" "select funnel_descuento_resolver(current_setting('kx.sol')::bigint,true);"
caso "QA M2: no se aprueba el descuento de quien ya no está en sala" "ERROR: ese cliente ya no está en la sala" gerente_ventas "$PEDIDO update funnel_prospectos set etapa='baja' where id=900101;" "select funnel_descuento_resolver(current_setting('kx.sol')::bigint,true);"
caso "QA M2: al cerrar, el pedido colgado se cierra" "reemplazada" vendedor "$PEDIDO" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4); $DUE select estado from funnel_descuento_solicitudes where id=current_setting('kx.sol')::bigint;"
caso "ciber H2: quien cerró no verifica su cierre" "ERROR: no podés verificar una venta en la que participaste" admin "$CERRADO" "$VER($CID,'verificado');"
caso "ciber H2: quien aprobó el descuento no verifica esa venta" "ERROR: no podés verificar una venta en la que participaste" gerente_ventas "$APROBADO update funnel_descuento_solicitudes set resuelto_por='gerente_ventas@prueba.kx' where id=current_setting('kx.sol')::bigint; select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4,current_setting('kx.sol')::bigint);" "$VER($CID,'verificado');"
caso "QA M4: dado de baja antes de verificar: no se verifica" "ERROR: ese cliente ya está de baja: solo se puede marcar que se arrepintió" verificador "$CERRADO update funnel_prospectos set etapa='baja' where id=900101;" "$VER($CID,'verificado');"
caso "QA M3: verificar después de observar conserva la nota" "no contestó" verificador "$CERRADO" "$VER($CID,'observado','no contestó'); $VER($CID,'verificado'); $DUE select verificacion_nota from funnel_contratos where prospecto_id=900101;"
caso "QA H2: se arrepintió: el socio queda vencido hoy" "true" verificador "$CERRADO" "$VER($CID,'arrepentido','x'); $DUE select (vencimiento<=current_date)::text from socios where id=(select socio_id from funnel_contratos where prospecto_id=900101);"
caso "QA M5: volver a cerrar tras arrepentirse pone al día el socio" "null|1000" admin "$CERRADO select set_config('request.jwt.claims','{\"role\":\"authenticated\",\"app_metadata\":{\"role\":\"verificador\"},\"sub\":\"'||md5('kx-verificador')||'\",\"email\":\"verificador@prueba.kx\"}',true); select funnel_contrato_verificar((select id from funnel_contratos where prospecto_id=900101),'arrepentido','x');" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4); $DUE select coalesce(contrato_cancelado_en::text,'null')||'|'||total_num::int from socios where id=(select socio_id from funnel_prospectos where id=900101);"
caso "ciber H7: enganche negativo: no existe" "ERROR" vendedor "$CERRADO" "update funnel_contratos set enganche=-500 where prospecto_id=900101;"
caso "ciber H7: contrato verificado: el enganche ya no se toca" "0" vendedor "$CERRADO update funnel_contratos set estado='verificado' where prospecto_id=900101;" "with u as (update funnel_contratos set enganche=10 where prospecto_id=900101 returning 1) select count(*) from u;"
caso "ciber2: enganche NaN: no existe" "ERROR" vendedor "$CERRADO" "update funnel_contratos set enganche='NaN' where prospecto_id=900101;"
caso "ciber2: enganche mayor que el contrato: no existe" "ERROR" vendedor "$CERRADO" "update funnel_contratos set enganche=999999 where prospecto_id=900101;"
caso "ciber2: un liner ajeno no da de baja un contrato por verificar" "ERROR: ese contrato está por verificar: la baja la marca el verificador («se arrepintió») o la gerencia de ventas" vendedor "$CERRADO update funnel_prospectos set vendedor_id=900022 where id=900101;" "update funnel_prospectos set etapa='baja' where id=900101;"
caso "ciber2: la gerencia de ventas sí puede dar esa baja" "1" gerente_ventas "$CERRADO" "with u as (update funnel_prospectos set etapa='baja' where id=900101 returning 1) select count(*) from u;"
caso "ciber2: quien cambió de puesto no verifica su venta vieja" "ERROR: no podés verificar una venta en la que participaste" verificador "$CERRADO set local session_replication_role = replica; update funnel_agentes set activo=false, user_id=md5('kx-verificador')::uuid where id=900021; set local session_replication_role = origin;" "$VER($CID,'verificado');"
caso "ciber2: retirar un aprobado no borra quién lo aprobó" "gerente_ventas@prueba.kx" vendedor "$APROBADO update funnel_descuento_solicitudes set resuelto_por='gerente_ventas@prueba.kx' where id=current_setting('kx.sol')::bigint;" "select funnel_descuento_retirar(900101); $DUE select resuelto_por from funnel_descuento_solicitudes where id=current_setting('kx.sol')::bigint;"
caso "membresías: solo la gerencia de ventas tiene el permiso" "admin,gerente_general,gerente_ventas" _dueno "" "select string_agg(rol_clave,',' order by rol_clave) from funnel_permisos where permiso='gestionar_membresias' and permitido;"
caso "permisos: verificar solo admin, gerencia de ventas y verificador" "admin,gerente_general,gerente_ventas,verificador" _dueno "" "select string_agg(rol_clave,',' order by rol_clave) from funnel_permisos where permiso='verificar_contratos' and permitido;"

echo "· bloque 6: comisiones y cabos sueltos"
GV="set local session_replication_role = replica; insert into funnel_agentes(id,nombre,rol,email,activo,peso) overriding system value values (900051,'GV','gerente_ventas','gv@prueba.kx',true,1); update funnel_agentes set gerente_id=900051 where id=900031; set local session_replication_role = origin;"
DIG="insert into auth.users(id,email,raw_app_meta_data) values (md5('kx-digitador')::uuid,'digitador@prueba.kx','{\"role\":\"digitador\"}') on conflict (id) do nothing; set local session_replication_role = replica; insert into funnel_agentes(id,nombre,rol,email,activo,peso,user_id) overriding system value values (900061,'D1','digitador','digitador@prueba.kx',true,1,md5('kx-digitador')::uuid); set local session_replication_role = origin;"
ARREP="$CERRADO select set_config('request.jwt.claims','{\"role\":\"authenticated\",\"app_metadata\":{\"role\":\"verificador\"},\"sub\":\"'||md5('kx-verificador')||'\",\"email\":\"verificador@prueba.kx\"}',true); select funnel_contrato_verificar((select id from funnel_contratos where prospecto_id=900101),'arrepentido','se echó para atrás');"
caso "TMK ya no edita las reglas de comisión" "0" gerente_tmk "" "with u as (update funnel_comision_reglas set tasa=10 where rol='tmk' returning 1) select count(*) from u;"
caso "el gerente de ventas sí" "1" gerente_ventas "" "with u as (update funnel_comision_reglas set tasa=2.5 where rol='tmk' returning 1) select count(*) from u;"
caso "una tasa de 60 %: no existe" "ERROR" gerente_ventas "" "update funnel_comision_reglas set tasa=60 where rol='tmk';"
caso "una tasa NaN: no existe" "ERROR" gerente_ventas "" "update funnel_comision_reglas set tasa='NaN' where rol='tmk';"
caso "un puesto inventado: no existe" "ERROR" gerente_ventas "" "insert into funnel_comision_reglas(rol,tasa) values ('primo',5);"
caso "nadie borra reglas" "ERROR" gerente_ventas "" "delete from funnel_comision_reglas where rol='tmk';"
caso "gestionar comisiones: solo gerencia de ventas, general y admin" "admin,gerente_general,gerente_ventas" _dueno "" "select string_agg(rol_clave,',' order by rol_clave) from funnel_permisos where permiso='gestionar_comisiones' and permitido;"
caso "la comisión del gerente de ventas va al gerente del closer" "900051" vendedor "$CON_CLOSER $SEG $GV" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4); $DUE select beneficiario_id from funnel_comisiones where rol='gerente_ventas' and contrato_id=$CID;"
caso "cambiar una regla no toca contratos ya cerrados" "30.00" gerente_ventas "$CERRADO" "update funnel_comision_reglas set tasa=10 where rol='vendedor'; $DUE select monto from funnel_comisiones where rol='vendedor' and contrato_id=$CID;"
caso "un digitador ya no cierra solo nombrándose" "ERROR: debes aparecer como uno de los roles del contrato que cerras" digitador "$CON_CLOSER $SEG $DIG" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,900061,4);"
caso "cancelados: gerencia de ventas ve reservas y enganche a devolver" "1|100" gerente_ventas "$ARREP insert into funnel_reservas(prospecto_id,destino) values (900101,'Cancún'); update funnel_contratos set enganche=100 where prospecto_id=900101;" "select reservas||'|'||enganche from funnel_contratos_cancelados() where cliente='pA';"
caso "el liner no ve cancelados" "ERROR: no autorizado" vendedor "$ARREP" "select count(*) from funnel_contratos_cancelados();"
caso "reabrir sin motivo: frena" "ERROR: escribí por qué se reabre" gerente_ventas "$ARREP" "select funnel_contrato_reabrir($CID,'');"
caso "el verificador no reabre" "ERROR: no autorizado" verificador "$ARREP" "select funnel_contrato_reabrir($CID,'error');"
caso "reabrir: vuelve a verificación, comisiones pendientes, socio restituido" "por_verificar|pendiente|socio|null|true" gerente_ventas "$ARREP" "select funnel_contrato_reabrir($CID,'lo marcaron por error'); $DUE select c.estado||'|'||string_agg(distinct m.estado,',')||'|'||p.etapa||'|'||coalesce(s.contrato_cancelado_en::text,'null')||'|'||(s.vencimiento>current_date)::text from funnel_contratos c join funnel_comisiones m on m.contrato_id=c.id join funnel_prospectos p on p.id=c.prospecto_id join socios s on s.id=c.socio_id where c.prospecto_id=900101 group by c.estado,p.etapa,s.contrato_cancelado_en,s.vencimiento;"
caso "no se reabre si ya tiene otro contrato vivo" "ERROR: ese cliente ya tiene otro contrato vivo" gerente_ventas "$ARREP select set_config('request.jwt.claims','{\"role\":\"authenticated\",\"app_metadata\":{\"role\":\"admin\"},\"email\":\"admin@prueba.kx\"}',true); select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4);" "select funnel_contrato_reabrir((select min(id) from funnel_contratos where prospecto_id=900101),'x');"
caso "la verificación avisa si el cliente tiene reservas" "1" verificador "$CERRADO insert into funnel_reservas(prospecto_id,destino) values (900101,'Cancún');" "select reservas from funnel_contratos_por_verificar() where cliente='pA';"
caso "diseño P1-1: la regla de una membresía reemplaza a la general (no se suman)" "50.00" gerente_ventas "$CON_CLOSER $SEG insert into funnel_comision_reglas(rol,tipo_membresia,tasa) values ('vendedor','x',5);" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4); $DUE select string_agg(monto::text,',') from funnel_comisiones where rol='vendedor' and contrato_id=$CID;"
caso "diseño P1-1: dos reglas activas iguales: no se puede" "ERROR" gerente_ventas "" "insert into funnel_comision_reglas(rol,tasa) values ('vendedor',4);"
caso "diseño P1-1: la del verificador también se reemplaza" "45.00" verificador "$CERRADO insert into funnel_comision_reglas(rol,tipo_membresia,monto_fijo) values ('verificador','x',45);" "$VER($CID,'verificado'); $DUE select string_agg(monto::text,',') from funnel_comisiones where rol='verificador' and contrato_id=$CID;"
caso "diseño P2-3: con enganche, reabrir exige confirmar que no se devolvió" "ERROR: confirmá que el enganche no se le devolvió al cliente" gerente_ventas "$ARREP update funnel_contratos set enganche=100 where prospecto_id=900101;" "select funnel_contrato_reabrir($CID,'error');"
caso "diseño P2-3: confirmándolo, se reabre" "por_verificar" gerente_ventas "$ARREP update funnel_contratos set enganche=100 where prospecto_id=900101;" "select funnel_contrato_reabrir($CID,'error',true); $DUE select estado from funnel_contratos where id=$CID;"
caso "ciber B1: un gerente de TMK no asigna el gerente de ventas de un closer" "ERROR: el gerente de ventas de alguien lo asigna el gerente general" gerente_tmk "$GV" "update funnel_agentes set gerente_id=900051 where id=900003;"
caso "ciber B1: el gerente de ventas no se pone de jefe de los closers" "ERROR: el gerente de ventas de alguien lo asigna el gerente general" gerente_ventas "$GV" "update funnel_agentes set gerente_id=900051 where id=900003;"
caso "ciber B1: el gerente general sí" "1" gerente_general "$GV" "with u as (update funnel_agentes set gerente_id=900051 where id=900003 returning 1) select count(*) from u;"
caso "ciber B1: el gerente asignado tiene que ser gerente de ventas" "ERROR: ese no es un gerente de ventas activo" gerente_general "$GV" "update funnel_agentes set gerente_id=900001 where id=900003;"
caso "ciber B1: si el «gerente» no es de ventas, la comisión no se paga" "null" vendedor "$CON_CLOSER $SEG $GV set local session_replication_role = replica; update funnel_agentes set rol='gerente_tmk' where id=900051; set local session_replication_role = origin;" "select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4); $DUE select coalesce(max(beneficiario_id)::text,'null') from funnel_comisiones where rol='gerente_ventas' and contrato_id=$CID;"
caso "ciber B2: el gerente del closer no verifica esa venta" "ERROR: no podés verificar una venta en la que participaste" gerente_ventas "$CON_CLOSER $SEG $GV set local session_replication_role = replica; update funnel_agentes set user_id=md5('kx-gerente_ventas')::uuid where id=900051; set local session_replication_role = origin; $ADM5 select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4);" "$VER($CID,'verificado');"
caso "ciber B2: quien reabrió no verifica" "ERROR: no podés verificar una venta en la que participaste" gerente_ventas "$ARREP select set_config('request.jwt.claims','{\"role\":\"authenticated\",\"app_metadata\":{\"role\":\"gerente_ventas\"},\"email\":\"gerente_ventas@prueba.kx\"}',true); select funnel_contrato_reabrir((select id from funnel_contratos where prospecto_id=900101),'error');" "$VER($CID,'verificado');"
caso "ciber B2: el gerente de ventas no se sube su comisión" "ERROR: la comisión del gerente de ventas la fija el gerente general" gerente_ventas "" "update funnel_comision_reglas set tasa=50 where rol='gerente_ventas';"
caso "ciber B2: el gerente general sí la fija" "1" gerente_general "" "with u as (update funnel_comision_reglas set tasa=1.5 where rol='gerente_ventas' returning 1) select count(*) from u;"
caso "ciber: una regla para una membresía que no existe: no" "ERROR" gerente_ventas "" "insert into funnel_comision_reglas(rol,tipo_membresia,tasa) values ('vendedor',' ',5);"
caso "ciber R4: reabrir devuelve al socio los datos de ESE contrato" "x|1000" gerente_ventas "$ARREP select set_config('request.jwt.claims','{\"role\":\"authenticated\",\"app_metadata\":{\"role\":\"admin\"},\"email\":\"admin@prueba.kx\"}',true); insert into funnel_membresias(tipo,precio) values ('zz',5000); select funnel_cerrar_contrato(900101,'zz','y',900021,900031,null,4); set local session_replication_role = replica; update funnel_contratos set estado='cancelado' where prospecto_id=900101 and tipo_membresia='zz'; set local session_replication_role = origin;" "select funnel_contrato_reabrir((select id from funnel_contratos where prospecto_id=900101 and tipo_membresia='x'),'error'); $DUE select s.tipo||'|'||s.total_num::int from socios s join funnel_prospectos p on p.socio_id=s.id where p.id=900101;"
GVATADO="$CON_CLOSER $SEG $GV insert into auth.users(id,email,raw_app_meta_data) values (md5('kx-gerente_ventas')::uuid,'gerente_ventas@prueba.kx','{\"role\":\"gerente_ventas\"}') on conflict (id) do nothing; set local session_replication_role = replica; update funnel_agentes set user_id=md5('kx-gerente_ventas')::uuid, email='gerente_ventas@prueba.kx' where id=900051; set local session_replication_role = origin; $ADM5 select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4);"
caso "ciber2 A1: el gerente del closer no se desata para verificar" "ERROR: el gerente de ventas de alguien lo asigna el gerente general" gerente_ventas "$GVATADO" "update funnel_agentes set user_id=null where id=900051;"
caso "ciber2 A1: ni desatado por otro verifica (tiene comisión en el contrato)" "ERROR: no podés verificar una venta en la que participaste" gerente_ventas "$GVATADO set local session_replication_role = replica; update funnel_agentes set user_id=null where id=900051; set local session_replication_role = origin;" "$VER($CID,'verificado');"
caso "ciber2 A2: otro gerente no se apropia del agente de un gerente" "ERROR" gerente_ventas "$GVATADO" "update funnel_agentes set user_id=md5('kx-otroB')::uuid where id=900051;"
caso "ciber2 A3: ni le cambia el puesto" "ERROR" supervisor_tmk "$GVATADO" "update funnel_agentes set rol='supervisor_tmk' where id=900051;"
caso "ciber2 A4: el gerente de ventas no se pone de supervisor del telemarketer" "ERROR: el gerente de ventas de alguien lo asigna el gerente general" gerente_ventas "$GV" "update funnel_agentes set supervisor_id=900051 where id=900002;"
caso "ciber2 A4: ni se sube la comisión de supervisor de TMK" "ERROR: la comisión del gerente de ventas la fija el gerente general" gerente_ventas "" "update funnel_comision_reglas set tasa=50 where rol='supervisor_tmk';"
caso "ciber2: un gerente de TMK no apaga a un gerente de ventas" "ERROR: a los gerentes y supervisores los da de alta el gerente general" gerente_tmk "$GV" "update funnel_agentes set activo=false where id=900051;"
caso "ciber2: atar una cuenta ajena a un agente: no" "ERROR: esa cuenta no es la de ese agente" gerente_tmk "" "update funnel_agentes set user_id=md5('kx-otroB')::uuid where id=900005;"
caso "ciber2 A7: el gerente general con un agente fantasma a su correo no verifica" "ERROR: no podés verificar una venta en la que participaste" gerente_general "$CON_CLOSER $SEG set local session_replication_role = replica; insert into funnel_agentes(id,nombre,rol,email,activo,peso) overriding system value values (900077,'fantasma','gerente_ventas','gerente_general@prueba.kx',true,1); update funnel_agentes set gerente_id=900077 where id=900031; set local session_replication_role = origin; $ADM5 select funnel_cerrar_contrato(900101,'x','y',900021,900031,null,4);" "$VER($CID,'verificado');"
caso "Equipo sigue andando: un gerente de TMK agrega un telemarketer" "1" gerente_tmk "" "with i as (insert into funnel_agentes(nombre,email,rol,peso) values ('Nuevo','nuevo@prueba.kx','tmk',1) returning 1) select count(*) from i;"
caso "Equipo sigue andando: y lo desactiva" "1" gerente_tmk "" "with u as (update funnel_agentes set activo=false where id=900004 returning 1) select count(*) from u;"
caso "nadie vacía tablas con TRUNCATE" "false|false|false" _dueno "" "select has_table_privilege('authenticated','public.socios','truncate')::text||'|'||has_table_privilege('anon','public.funnel_membresias','truncate')::text||'|'||has_table_privilege('authenticated','public.funnel_permisos','truncate')::text;"

echo "── $((N-FALLAS))/$N verdes"
[ "$FALLAS" -eq 0 ]
